# baseURL = 'https://b32b677b.hugo-final.pages.dev'
defaultContentLanguage = 'en'
enableRobotsTXT = true
paginate=10

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.renderer]
unsafe = true
    
[params]
facebookUrl = "https://facebook.com/pl.seqred"
facebookAppId = "409771854443150"
facebookAdmins = "100004293542420,100070750539591"
linkedInUrl = "https://linkedin.com/company/seqred"
twitterUrl = "https://twitter.com/seqred_"
twitter = "@seqred_"
ogimage = "/img/matrix.jpg"

[permalinks]
news = "/:year/:month/:filename"

[build]
  writeStats = true

[languages]

[languages.en]
    title = "SEQRED | Secure OT and IoT - Cybersecurity audits - Cybersecurity advisory"
    weight = 1
    languageName = 'English'
    languageCode = 'en-GB'

    [[languages.en.menu.main]]
        identifier = "Assessment"
        name = "ASSESSMENT"
        url = "/"
        weight = 1

    [[languages.en.menu.main]]
        name = "Industrial Control Systems Security Audit"
        url = "/services/ot-audit/"
        weight = 1
        parent = "Assessment"

    [[languages.en.menu.main]]
        name = "OT Audit"
        url = "/"
        weight = 1
        parent = "Assessment"
        
    [[languages.en.menu.main]]
        name = "Cybersecurity Bill of Materials"
        url = "/services/cbom-en/"
        weight = 1
        parent = "Assessment"
        
    [[languages.en.menu.main]]
        name = "Penetration tests"
        url = "/services/penetration-tests/"
        weight = 1
        parent = "Assessment"
        
    [[languages.en.menu.main]]
        name = "Security code review"
        url = "/services/security-code-review/"
        weight = 1
        parent = "Assessment"
        
    [[languages.en.menu.main]]
        name = "Red Team"
        url = "/services/red-teaming-2/"
        weight = 1
        parent = "Assessment"
        
    [[languages.en.menu.main]]
        name = "Cloud Services Security"
        url = "/services/cloud-services-security/"
        weight = 1
        parent = "Assessment"
        
    [[languages.en.menu.main]]
        name = "KSC Audit"
        url = "/"
        weight = 1
        parent = "Assessment"
        
    [[languages.en.menu.main]]
        name = "Mobile Device Security"
        url = "/services/mobile-device-security/"
        weight = 1
        parent = "Assessment"

    [[languages.en.menu.main]]
        identifier = "Planning"
        name = "PLANNING"
        url = "/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Projektowanie"
        url = "/"
        weight = 2
        parent = "PLANNING"

    [[languages.en.menu.main]]
        name = "Projektowanie mechanizmów kontrolnych I rozwiązań bezpieczeństwa"
        url = "/pl/"
        weight = 2
        parent = "PLANNING"

    [[languages.en.menu.main]]
        name = "Secure product"
        url = "/pl/"
        weight = 2
        parent = "PLANNING"

    [[languages.en.menu.main]]
        name = "DevelopmentChmura"
        url = "/pl/"
        weight = 2
        parent = "PLANNING"

    [[languages.en.menu.main]]
        name = "Segmentacja I separacja Sieci"
        url = "/pl/"
        weight = 2
        parent = "PLANNING"

    [[languages.en.menu.main]]
        name = "Security Architect As A Service"
        url = "/pl/"
        weight = 2
        parent = "PLANNING"

    [[languages.en.menu.main]]        
        identifier = "WDRAŻANIE"
        name = "WDRAŻANIE"
        url = "/en/products/"
        weight = 3
    
    [[languages.en.menu.main]]
        name = "Wdrażanie rozwiązań bezpieczeństwa"
        url = "/pl/"
        weight = 3
        parent = "WDRAŻANIE"
            
    [[languages.en.menu.main]]
        name = "Chmura"
        url = "/pl/"
        weight = 3
        parent = "WDRAŻANIE"
            
    [[languages.en.menu.main]]
        name = "Threat Intelligence"
        url = "/services/open-source-intelligence/"
        weight = 3
        parent = "WDRAŻANIE"
            
    [[languages.en.menu.main]]
        name = "Ami"
        url = "/services/ami-system-security/"
        weight = 3
        parent = "WDRAŻANIE"
            
    [[languages.en.menu.main]]
        name = "Fortinet"
        url = "/pl/"
        weight = 3
        parent = "WDRAŻANIE"
            
    [[languages.en.menu.main]]
        name = "Nozomi"
        url = "/pl/"
        weight = 3
        parent = "WDRAŻANIE"
            
    [[languages.en.menu.main]]
        name = "Honeywell"
        url = "/pl/"
        weight = 3
        parent = "WDRAŻANIE"
            
    [[languages.en.menu.main]]
        name = "IBM"
        url = "/pl/"
        weight = 3
        parent = "WDRAŻANIE"
            
    [[languages.en.menu.main]]
        name = "eSecure"
        url = "/pl/"
        weight = 3
        parent = "WDRAŻANIE"

    [[languages.en.menu.main]]
        identifier = "Utrzymanie"
        name = "UTRZYMANIE"
        url = "/"
        weight = 4
                    
    [[languages.en.menu.main]]
        name = "Utrzymanie mechanizmów bezpieczeństwa"
        url = "/pl/"
        weight = 4
        parent = "UTRZYMANIE"
                    
    [[languages.en.menu.main]]
        name = "Chmura"
        url = "/pl/"
        weight = 4
        parent = "UTRZYMANIE"
                    
    [[languages.en.menu.main]]
        name = "Zarządzanie bezpieczeństwem środowiska O365"
        url = "/pl/"
        weight = 4
        parent = "UTRZYMANIE"
                    
    [[languages.en.menu.main]]
        name = "Security Architect As A Service"
        url = "/pl/"
        weight = 4
        parent = "UTRZYMANIE"                  

    [[languages.en.menu.main]]
        identifier = "Knowledge"
        name = "KNOWLEDGE"
        url = "/knowledge/"
        weight = 5

[languages.pl]
    title = 'SEQRED | Bezpieczne OT i IoT - Audyty bezpieczeństwa - Cyberbezpieczeństwo'
    weight = 1
    languageName = 'Polski'
    languageCode = 'pl'
        
    [[languages.pl.menu.main]]
        identifier = "Ocena"
        name = "OCENA"
        url = "/"
        weight = 1

    [[languages.pl.menu.main]]
        name = "Ocena efektywności stosowanych mechanizmów kontrolnych"
        url = "/"
        weight = 1
        parent = "Ocena"

    [[languages.pl.menu.main]]
        name = "Audyt OT"
        url = "/"
        weight = 1
        parent = "Ocena"
        
    [[languages.pl.menu.main]]
        name = "CBOM"
        url = "/"
        weight = 1
        parent = "Ocena"
        
    [[languages.pl.menu.main]]
        name = "Testy penetracyjne"
        url = "/pl/services/testy-penetracyjne/"
        weight = 1
        parent = "Ocena"
        
    [[languages.pl.menu.main]]
        name = "Audyt bezpieczeństwa kodu"
        url = "/pl/services/audyt-kodu/"
        weight = 1
        parent = "Ocena"
        
    [[languages.pl.menu.main]]
        name = "Red Team"
        url = "/pl/services/red-team/"
        weight = 1
        parent = "Ocena"
        
    [[languages.pl.menu.main]]
        name = "Chmura"
        url = "/pl/services/uslugi-chmurowe/"
        weight = 1
        parent = "Ocena"
        
    [[languages.pl.menu.main]]
        name = "Audyt KSC"
        url = "/pl/services/audyt-ksc/"
        weight = 1
        parent = "Ocena"
        
    [[languages.pl.menu.main]]
        name = "Urządzenia mobilne"
        url = "/pl/services/audyt-bezpieczenstwa-urzadzen-mobilnych/"
        weight = 1
        parent = "Ocena"

    [[languages.pl.menu.main]]
        identifier = "Projektowanie"
        name = "PROJEKTOWANIE"
        url = "/"
        weight = 2

    [[languages.pl.menu.main]]
        name = "Projektowanie"
        url = "/pl/"
        weight = 2
        parent = "PROJEKTOWANIE"

    [[languages.pl.menu.main]]
        name = "Projektowanie mechanizmów kontrolnych I rozwiązań bezpieczeństwa"
        url = "/pl/"
        weight = 2
        parent = "PROJEKTOWANIE"

    [[languages.pl.menu.main]]
        name = "Secure product"
        url = "/pl/"
        weight = 2
        parent = "PROJEKTOWANIE"

    [[languages.pl.menu.main]]
        name = "DevelopmentChmura"
        url = "/pl/"
        weight = 2
        parent = "PROJEKTOWANIE"

    [[languages.pl.menu.main]]
        name = "Segmentacja I separacja Sieci"
        url = "/pl/services/segmentacja-sieci/"
        weight = 2
        parent = "PROJEKTOWANIE"

    [[languages.pl.menu.main]]
        name = "Security Architect As A Service"
        url = "/pl/"
        weight = 2
        parent = "PROJEKTOWANIE"

    [[languages.pl.menu.main]]        
        identifier = "WDRAŻANIE"
        name = "WDRAŻANIE"
        url = "/"
        weight = 3
    
    [[languages.pl.menu.main]]
        name = "Wdrażanie rozwiązań bezpieczeństwa"
        url = "/pl/"
        weight = 3
        parent = "WDRAŻANIE"
            
    [[languages.pl.menu.main]]
        name = "Chmura"
        url = "/pl/"
        weight = 3
        parent = "WDRAŻANIE"
            
    [[languages.pl.menu.main]]
        name = "Threat Intelligence"
        url = "/services/open-source-intelligence/"
        weight = 3
        parent = "WDRAŻANIE"
            
    [[languages.pl.menu.main]]
        name = "Ami"
        url = "/services/ami-system-security/"
        weight = 3
        parent = "WDRAŻANIE"
            
    [[languages.pl.menu.main]]
        name = "Fortinet"
        url = "/pl/"
        weight = 3
        parent = "WDRAŻANIE"
            
    [[languages.pl.menu.main]]
        name = "Nozomi"
        url = "/pl/"
        weight = 3
        parent = "WDRAŻANIE"
            
    [[languages.pl.menu.main]]
        name = "Honeywell"
        url = "/pl/"
        weight = 3
        parent = "WDRAŻANIE"
            
    [[languages.pl.menu.main]]
        name = "IBM"
        url = "/pl/"
        weight = 3
        parent = "WDRAŻANIE"
            
    [[languages.pl.menu.main]]
        name = "eSecure"
        url = "/pl/"
        weight = 3
        parent = "WDRAŻANIE"
        
    [[languages.pl.menu.main]]
        identifier = "Utrzymanie"
        name = "UTRZYMANIE"
        url = "/"
        weight = 4
                    
    [[languages.pl.menu.main]]
        name = "Utrzymanie mechanizmów bezpieczeństwa"
        url = "/pl/"
        weight = 4
        parent = "UTRZYMANIE"
                    
    [[languages.pl.menu.main]]
        name = "Chmura"
        url = "/pl/"
        weight = 4
        parent = "UTRZYMANIE"
                    
    [[languages.pl.menu.main]]
        name = "Zarządzanie bezpieczeństwem środowiska O365"
        url = "/pl/"
        weight = 4
        parent = "UTRZYMANIE"
                    
    [[languages.pl.menu.main]]
        name = "Security Architect As A Service"
        url = "/pl/"
        weight = 4
        parent = "UTRZYMANIE"                  

    [[languages.pl.menu.main]]
        identifier = "Knowledge"
        name = "WIEDZA"
        url = "/wiedza/"
        weight = 5

    [[languages.en.menu.footer]]
        identifier = "About"
        name = "ABOUT"
        url = "/about-us/"
        weight = 1

    [[languages.en.menu.footer]]
        identifier = "Services"
        name = "SERVICES"
        url = "/services/"
        weight = 2

    [[languages.en.menu.footer]]
        identifier = "Events"
        name = "EVENTS"
        url = "/events/"
        weight = 3

    [[languages.en.menu.footer]]
        identifier = "Blog"
        name = "BLOG"
        url = "/blog/"
        weight = 4

    [[languages.en.menu.footer]]
        identifier = "Contact"
        name = "CONTACT"
        url = "/contact/"
        weight = 5

    [[languages.pl.menu.footer]]
        identifier = "About"
        name = "ABOUT"
        url = "/pl/about-us/"
        weight = 1

    [[languages.pl.menu.footer]]
        identifier = "Services"
        name = "SERVICES"
        url = "/pl/services/"
        weight = 2

    [[languages.pl.menu.footer]]
        identifier = "Events"
        name = "EVENTS"
        url = "/pl/events/"
        weight = 3

    [[languages.pl.menu.footer]]
        identifier = "Blog"
        name = "BLOG"
        url = "/pl/blog/"
        weight = 4

    [[languages.pl.menu.footer]]
        identifier = "Contact"
        name = "CONTACT"
        url = "/kontakt/"
        weight = 5


