# baseURL = 'https://b32b677b.hugo-final.pages.dev'
defaultContentLanguage = 'en'
enableRobotsTXT = true
paginate=10

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.renderer]
unsafe = true
    
[params]
facebookUrl = "https://facebook.com/pl.seqred"
facebookAppId = "409771854443150"
facebookAdmins = "100004293542420,100070750539591"
linkedInUrl = "https://linkedin.com/company/seqred"
twitterUrl = "https://twitter.com/seqred_"
twitter = "@seqred_"
ogimage = "/img/matrix.jpg"

[permalinks]
news = "/:year/:month/:filename"

[build]
  writeStats = true

[languages]

[languages.en]
    title = "SEQRED | Secure OT and IoT - Cybersecurity audits - Cybersecurity advisory"
    weight = 1
    languageName = 'English'
    languageCode = 'en-GB'

    [[languages.en.menu.main]]
        identifier = "Assessment"
        name = "ASSESSMENT"
        url = "/"
        weight = 1

    [[languages.en.menu.main]]
        name = "Industrial Control Systems Security Audit"
        url = "/services/ot-audit/"
        weight = 1
        parent = "Assessment"

    [[languages.en.menu.main]]
        name = "OT Audit"
        url = "/"
        weight = 1
        parent = "Assessment"
        
    [[languages.en.menu.main]]
        name = "Cybersecurity Bill of Materials"
        url = "/services/cbom-en/"
        weight = 1
        parent = "Assessment"
        
    [[languages.en.menu.main]]
        name = "Penetration tests"
        url = "/services/penetration-tests/"
        weight = 1
        parent = "Assessment"
        
    [[languages.en.menu.main]]
        name = "Security code review"
        url = "/services/security-code-review/"
        weight = 1
        parent = "Assessment"
        
    [[languages.en.menu.main]]
        name = "Red Team"
        url = "/services/red-teaming-2/"
        weight = 1
        parent = "Assessment"
        
    [[languages.en.menu.main]]
        name = "Cloud Services Security"
        url = "/services/cloud-services-security/"
        weight = 1
        parent = "Assessment"
        
    [[languages.en.menu.main]]
        name = "KSC Audit"
        url = "/"
        weight = 1
        parent = "Assessment"
        
    [[languages.en.menu.main]]
        name = "Mobile Device Security"
        url = "/services/mobile-device-security/"
        weight = 1
        parent = "Assessment"

    [[languages.en.menu.main]]
        identifier = "Services"
        name = "Services"
        url = "/services/"
        weight = 2

    [[languages.en.menu.main]]        
        identifier = "Products"
        name = "PRODUCTS"
        url = "/en/products/"
        weight = 3
    
    [[languages.en.menu.main]]
        identifier = "Events"
        name = "EVENTS"
        url = "/events/"
        weight = 4

     [[languages.en.menu.main]]
        identifier = "News"
        name = "NEWS"
        url = "/news/"
        weight = 5
    
    [[languages.en.menu.main]]
        identifier = "Career"
        name = "CAREER"
        url = "/career/"
        weight = 6
    
    [[languages.en.menu.main]]
        identifier = "Blog"
        name = "BLOG"
        url = "/blog/"
        weight = 7

    [[languages.en.menu.main]]
        identifier = "Knowledge"
        name = "KNOWLEDGE"
        url = "/knowledge/"
        weight = 8

    [[languages.en.menu.main]]
        identifier = "Contact"
        name = "CONTACT"
        url = "/contact/"
        weight = 9

[languages.pl]
    title = 'SEQRED | Bezpieczne OT i IoT - Audyty bezpieczeństwa - Cyberbezpieczeństwo'
    weight = 1
    languageName = 'Polski'
    languageCode = 'pl'
        
    [[languages.pl.menu.main]]
        identifier = "Ocena"
        name = "OCENA"
        url = "/"
        weight = 1

    [[languages.pl.menu.main]]
        name = "Ocena efektywności stosowanych mechanizmów kontrolnych"
        url = "/"
        weight = 1
        parent = "Ocena"

    [[languages.pl.menu.main]]
        name = "Audyt OT"
        url = "/"
        weight = 1
        parent = "Ocena"
        
    [[languages.pl.menu.main]]
        name = "CBOM"
        url = "/"
        weight = 1
        parent = "Ocena"
        
    [[languages.pl.menu.main]]
        name = "Testy penetracyjne"
        url = "/pl/services/testy-penetracyjne/"
        weight = 1
        parent = "Ocena"
        
    [[languages.pl.menu.main]]
        name = "Audyt bezpieczeństwa kodu"
        url = "/pl/services/audyt-kodu/"
        weight = 1
        parent = "Ocena"
        
    [[languages.pl.menu.main]]
        name = "Red Team"
        url = "/pl/services/red-team/"
        weight = 1
        parent = "Ocena"
        
    [[languages.pl.menu.main]]
        name = "Chmura"
        url = "/pl/services/uslugi-chmurowe/"
        weight = 1
        parent = "Ocena"
        
    [[languages.pl.menu.main]]
        name = "Audyt KSC"
        url = "/pl/services/audyt-ksc/"
        weight = 1
        parent = "Ocena"
        
    [[languages.pl.menu.main]]
        name = "Urządzenia mobilne"
        url = "/pl/services/audyt-bezpieczenstwa-urzadzen-mobilnych/"
        weight = 1
        parent = "Ocena"

    [[languages.pl.menu.main]]
        identifier = "Services"
        name = "USŁUGI"
        url = "/uslugi/"
        weight = 2

    [[languages.pl.menu.main]]
        identifier = "Products"
        name = "PRODUKTY"
        url = "/produkty/"
        weight = 3
        
    [[languages.pl.menu.main]]
        identifier = "Events"
        name = "WYDARZENIA"
        url = "/wydarzenia/"
        weight = 4

     [[languages.pl.menu.main]]
        identifier = "News"
        name = "AKTUALNOŚCI"
        url = "/pl/news/"
        weight = 5

    [[languages.pl.menu.main]]
        identifier = "Career"
        name = "KARIERA"
        url = "/pl/career/"
        weight = 6

    [[languages.pl.menu.main]]
        identifier = "Blog"
        name = "BLOG"
        url = "/pl/blog/"
        weight = 7

    [[languages.pl.menu.main]]
        identifier = "Knowledge"
        name = "WIEDZA"
        url = "/wiedza/"
        weight = 8

    [[languages.pl.menu.main]]
        identifier = "Contact"
        name = "KONTAKT"
        url = "/kontakt/"
        weight = 9

    [[languages.en.menu.footer]]
        identifier = "Services"
        name = "SERVICES"
        url = "/services"
        weight = 1

    [[languages.en.menu.footer]]
        name = "IT Consulting"
        url = "/it-consulting"
        weight = 1
        parent ="Services"

    [[languages.en.menu.footer]]
        name = "Development"
        url = "/development"
        weight = 1
        parent ="Services"

    [[languages.en.menu.footer]]
        name = "Cloud"
        url = "/cloud"
        weight = 1
        parent ="Services"

    [[languages.en.menu.footer]]
        name = "Support"
        url = "/support"
        weight = 1
        parent ="Services"